version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: Vijay
      POSTGRES_PASSWORD: vijaysb
      POSTGRES_DB: tododb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

